# Rust installation
- name: Check for Cargo
  ansible.builtin.shell: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: Download Rustup installer
  when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: Install Rust
  when: cargo_exists is failed
  ansible.builtin.shell: /tmp/sh.rustup.rs -y

# Go installation
- name: Install Go with Homebrew
  community.general.homebrew:
    name: go
    state: present