---
- name: Install personal tech stack for macOS
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    hack_version: "3.003"
    nerd_symbol_version: "3.0.01"
    bottom_version: "0.9.1"
    tmux_plugins_path: "~/.tmux/plugins/"

  tasks:
    - name: Setup core components
      ansible.builtin.include_tasks: "tasks/core.yaml"

    - name: Install programming languages (Rust and Go)
      ansible.builtin.include_tasks: "tasks/programming_languages.yaml"

    - name: Install fonts
      ansible.builtin.include_tasks: "tasks/fonts.yaml"

    - name: Install additional tooling
      ansible.builtin.include_tasks: "tasks/tools.yaml"

    - name: Install Docker and Kubernetes tools
      ansible.builtin.include_tasks: "tasks/docker_k8s.yaml"
